{% set name = "superblockify" %}
{% set version = "1.0.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/superblockify-{{ version }}.tar.gz
  sha256: 32ef497361502d3f57480512ee987a9463eb296e265aef9fc751fc4ebb1bd338

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - pip
  run:
    - python >={{ python_min }}
    - osmnx >=1.6.0
    - geopandas
    - rasterio
    - shapely
    - numba
    - scipy
    - tqdm
    - contextily
    - ruamel.yaml
    - seaborn
    - psutil
    - typing_extensions

test:
  imports:
    - superblockify
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://superblockify.city/
  summary: Automated Generation, Visualization, and Analysis of potential Superblocks in Cities
  license: AGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://superblockify.city/
  dev_url: https://github.com/NERDSITU/superblockify

extra:
  recipe-maintainers:
    - cbueth
