{% set name = "superblockify" %}
{% set version = "1.0.0rc9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/superblockify-{{ version }}.tar.gz
  sha256: 471778f0787b0682fac13b42308aaf93a262180a13070d1d176659f7c96984bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.2
    - pip
  run:
    - python >=3.10
    - osmnx >=1.6.0
    - geopandas
    - rasterio
    - shapely
    - numba
    - scipy
    - tqdm
    - contextily
    - ruamel.yaml
    - seaborn
    - psutil
    - typing_extensions

test:
  imports:
    - superblockify
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NERDSITU/superblockify
  summary: Automated Generation, Visualization, and Analysis of potential Superblocks in Cities
  license: AGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://nerdsitu.github.io/superblockify/
  dev_url: https://github.com/NERDSITU/superblockify

extra:
  recipe-maintainers:
    - cbueth
